source 'https://rubygems.org'
gem 'rails', '~> 7.0.0'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'authie'
gem 'kaminari'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt', '>= 3.1.12' # 3.1.11 fails on Ubuntu with HashError
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey'
gem 'nifty-attachments'
gem 'puma'
gem 'moonrope'
gem 'florrick'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet'
gem 'premailer'
gem 'rack-custom-proxies'
gem 'log_logins'

group :development, :test do
  gem 'listen'
  gem 'annotate'
  gem 'webmock'
  gem 'capybara'
end

gem 'sassc'
gem 'vultr', '~> 1.0' # trigger vultr VM restarts, v2 looks like a big rewrite
gem 'rack-attack'