[variables]
RAILS_ENV="production"
RUBY_CONFIGURE_OPTS="--with-jemalloc --disable-install-rdoc"

# - 15-20 sec to install apt packages
# - 100 sec to install ruby 2.6.9 (no doc, including 20 sec to install openssl 1.1.1)
# - 26 sec to install gems (200 with sassc compilation -_-)
# - 5 sec precompile
# Total: ~150, but 40sec with ruby and APT cached

[phases.setup]
aptPkgs = ["...", "libjemalloc-dev"]
# Below is an attempt to cache ruby and gems (worked for ruby) https://github.com/railwayapp/nixpacks/pull/817
# cmds = ["cp -r /cache/.rbenv /root", "curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash -s stable && printf '\\neval \"$(rbenv init -)\"' >> /root/.profile && . /root/.profile && rbenv install -s 2.6.9 && rbenv global 2.6.9 && gem install bundler:2.3.21 --no-document --conservative", "cp -r /root/.rbenv /cache"]
# cacheDirectories = ["/cache/.rbenv"]

[phases.build]
# cacheDirectories = ["/cache/.rbenv"]
# Supposed to be automatic but it stopped working...
cmds = ["bundle exec rails assets:precompile"]
